### ISSUE TITLE
Multiple Arguments in Subscript Closures

### ISSUE THREAD

**Issue by SerenadeX** [CrossWaterBridge/Mole#1]
Instead of writing each possible server method with the following:

``` swift
server["someMethodWithParameters"] = { params in
...
}
```

We could also optionally put them in as follows:

``` swift
server ["someMethodWithParameters"] = { one, two in
...
}
```

I think this is possible but not sure if its something desired in the design.

**Comment by SerenadeX** [comment]
Not sure if this is going anywhere.  If someone wants this we can reopen it.

**Comment by hiltonc** [comment]
Definitely desirable. I just don't know how to do it.

**Comment by SerenadeX** [comment]
Well if we can figure out a way to do it, lets do it, but I don't think there is any priority on getting it done.
